XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX
XXXXXXXXX XXX XXXXXXXXXX XXXXXXXX X XXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXXX
XXX XXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXX
XXXXXX
	XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX XXXX XXXX X
X
	XXXX X XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXX X X
	XXX XXXXXX X XXXXXXXX X XXXX X XXXXXXXXXXX X
	XXX XXXXX X XXX XXXXXXX XXXXXX X X
	XXX XXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X

	XX X XXXXXXX X
		XXXXXX XXXXXXXX X X X
	XXXX
		XXXXXX XX X
X

XXX XXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXX
X
	XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X
	XXX
	X
		XX X XXXXXXXXXXXXXXXXXXXXX X
		X
			XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXX XX XXXX XXXXXX X X X X
			XXXXXXXXXXXXXXXXXXXXX XXXXXXXX X X
		X
	X
	XXXXX XXX XX
X

XXXXXXXX XXXXXXXXX XXXXXXX X
	        XXX XXXXXXX X XXXXXXXXXXX
	        XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
	        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXX X X X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXX X XX XXX XXXXXXXX XXXXXX XX XXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX
    XXXXX X
            XX XXXXXXXXXXXXXXXXXXXX X XX XX XXXXXX XXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                X
        X
X

XXXXXXXX XXXXXXXX
X
	XXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XX
	XXXXXXXXXXXXXXXXXXXX
X

XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
